<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* help@getflywheel.com.                                                           */
/***********************************************************************************/

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'http://');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);
define('WP_MEMORY_LIMIT', '128M');




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db6511986984');
define('DB_USER', 'fw1090300350');
define('DB_PASSWORD', 'ERTaDPUqshWpGwdklR7LoNtU1hybWf');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
$table_prefix  = 'wp_1de3k9csmm_';


/****************************************************************************/
/*                          Plugin Configuration                            */
/****************************************************************************/




/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          'C-3vVK|><lB5<drRPX[(`b,<I<Z`DP2r7?*!/_b!Nfwj_hXPW^s3J<L<DDM98eYb');
define('SECURE_AUTH_KEY',   'aMF^*S@M##F/=LMh5/=FdLy[X.T_Vf3^0^h#_9I72:s[c,g!O@Ke@[OMw&4{3K7N');
define('LOGGED_IN_KEY',     '<z8T<]g$rJ.jqEMZ>TbIH/tr3eb!|@4XO6nk2rUF,7gL/G4^`hERdaPGG,NnihtD');
define('NONCE_KEY',         'Z_Y|d19c^@{d/C(*kXAIEly|tS]h`)r,n?&Gkm}wpl8A}v0WpGdCe-dofu?i8TFt');
define('AUTH_SALT',         '_*Ztkzos|43_Kj=i3}L`)&}wga-PSsk+|_pCE0|k/Wjd;3tJ@n)|..wh7nvW4I4$');
define('SECURE_AUTH_SALT',  '{YU64]L^c25q2KFRkL6@J,8a_=>5i+v8Um2cD0+;X1}8$|Zgev4f2B;Slj^%RKo`');
define('LOGGED_IN_SALT',    '4zYP}B/LR?f?uc);5C#a49)#XyFjjn@Rl66_?k6Jv%w2R@N,NhXMAH#}6</ZO:L=');
define('NONCE_SALT',        '$Ej,!Ak*].}oUkKbPnP#t#2dNF2lE;r}4~o1g3lmqjVf0wR=(}eG=z+9?P>Ba<[9');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/
define('WPLANG', '');
define('WP_DEBUG', false);
define('WP_CACHE', false);
define('WP_DEBUG_LOG', false);




/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
